### ISSUE TITLE
Get validation result from a should expression

### ISSUE THREAD

**Issue by cdlm** [dionisiydk/StateSpecs#7]
All the DSL messages in the *expressions* protocol of `SpecOfShouldExpression` do `^ self verify: …` as if that was intended to return something useful, but `verify:` does not return the validation result, it only raises it, which looks like an oversight.

I have a use case where I'd like to gather the results of multiple validations for an object instead of immediately complaining about the first one in evaluation order. This would allow to report a list of diagnostics, maybe after selecting the most critical ones.

**Comment by dionisiydk** [comment]
Hi Damien.
I wonder how you are trying to use should expressions?
The intention was to always fail. It is DSL over real spec objects to create them and validate in one code line.
If you need the result you should create Spec instance manually and call #validate:. There is another class based DSL to instantiate those objects in readable form. For example:
```Smalltalk
(Kind of: Point) validate: 2@3.
(Equal to: 2@3) validate: 10@20.
``` 
Validation never failed. It returns validation result instances: success or failure. There are hierarchy of failures.
Specs can be composed using #or, #and and #not messages..
So what is your purpose?

**Comment by cdlm** [comment]
I simply prefer the should-DSL to the class-based one to express validations, because they read like sentences. The class-based ones read like point-free partial applications in haskell, and composing the validation instances explicitly is just too tedious 😒

So I was looking for a way to enable both raising and returning the validation result with the should-DSL (I understand that raising `SpecOfFailed` is needed for the SUnit assertion use-case). It seems there are at least two solutions:
- the one I'm hinting at here is to enable `[ 42 should be < 51 ] on: SpecOfFailed do: #resume`.
- I guess I could subclass `SpecOfShouldExpression` with a different `#verify:` implementation that does not raise `SpecOfFailed`, and perhaps plug it behind a different verb than `#should`, but that sound a bit overkill…

**Comment by dionisiydk** [comment]
Interesting. I merged your code. But I would like to see your use case

**Comment by dionisiydk** [comment]
done
